name: Build and Deploy Node.js Functions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - run: npm install
      working-directory: ./server 
    - run: npm run build
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: backend-mern-stack
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_11AD45C5F8864EE8B23E75B17B59071D }}

